In [1]:
import pandas as pd
import numpy as np
data = np.arange(12).reshape(4, 3)
print(data)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [2]:
df = pd.DataFrame( data, index = ['one', 'two', 'three', 'four'], columns=['X', 'Y', 'Z'])

1. Get column 'Y'
2. Get row 'three' (by name)
3. Get the second and fourth row (by index)
4. Get the columns 'Y' and 'Z' of rows 'two' and 'three'